# Generated by Django 6.0.1 on 2026-02-18 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('skills', models.JSONField(default=list, help_text='["Cloud", "DevOps", "DSA"]')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['display_order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list, help_text='["Docker", "Flask", "Redis"]')),
                ('github_link', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('dockerhub_link', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('live_demo_link', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_date'],
            },
        ),
    ]
