# Generated by Django 6.0.1 on 2026-02-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_certificate_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
