# Generated by Django 6.0.1 on 2026-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_certificate_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-certificate', max_length=50)),
                ('certificate_url', models.URLField(blank=True, help_text='Link to view certificate')),
                ('focus_areas', models.CharField(blank=True, help_text='Comma-separated list of focus areas', max_length=500)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True, help_text='Detailed description for project page')),
                ('icon', models.CharField(default='fas fa-code-branch', help_text='Font Awesome icon class', max_length=50)),
                ('architecture', models.CharField(choices=[('microservices', 'Microservices'), ('monolithic', 'Monolithic'), ('devops', 'DevOps')], default='devops', max_length=20)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='docker-badge', max_length=20)),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies', max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('dockerhub_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('docker_pulls', models.IntegerField(blank=True, default=0)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
