# Generated by Django 6.0.1 on 2026-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_certification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
